name: CMake

on: [push,pull_request]

jobs:
  build_example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: cmake -B build
      - run: cmake --build build
